// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfuojbdwzypasskvzicv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmdW9qYmR3enlwYXNza3Z6aWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NzY2ODEsImV4cCI6MjA1NDU1MjY4MX0.MWfnrFqTNrbvu4fapwy0Bs-m-Y2JY2P5dlvnR0nHMdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);